apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: tracee
  name: tracee
spec:
  selector:
    matchLabels:
      app: tracee
  template:
    metadata:
      labels:
        app: tracee
      name: tracee
    spec:
      containers:
      - image: aquasec/tracee:latest
        imagePullPolicy: Always
        env:
        - name: WEBHOOK_URL
          value: http://webhook:2801
        args:
          - ./tracee-ebpf --output=format:gob | ./tracee-rules --input-tracee=file:stdin
            --input-tracee=format:gob --webhook $WEBHOOK_URL --webhook-template /templates/falcosidekick.tmpl --webhook-content-type application/json
        command:
          - /bin/sh
          - -c
        ports:
        - containerPort: 8096
          protocol: TCP
        name: tracee
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-tracee
          mountPath: /tmp/tracee
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules/
          readOnly: true
        - name: tracee-templates
          mountPath: /templates
      hostPID: true
      volumes:
      - hostPath:
          path: /tmp/tracee
        name: tmp-tracee
      - hostPath:
          path: /usr/src
        name: usr-src
      - hostPath:
          path: /lib/modules
        name: lib-modules
      - configMap:
          name: tracee-templates
        name: tracee-templates

